export const services = [
  {
    id: 1,
    title: "Bath & Brush",
    description: "A thorough bath with premium organic shampoo, blow-dry, and a complete brush-out to leave your pet feeling fresh and clean.",
    price: "$35",
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80",
  },
  {
    id: 2,
    title: "Bath & Tidy",
    description: "Includes bath, brush, nail trim, ear cleaning, and a neat sanitary trim for a well-groomed look.",
    price: "$50",
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1553882809-a4f57e595701?w=600&q=80",
  },
  {
    id: 3,
    title: "Full Grooming",
    description: "Our complete grooming package: bath, brush, haircut, nail trim, ear cleaning, and styling. Everything your pet needs.",
    price: "$75",
    duration: "90 min",
    image: "https://images.unsplash.com/photo-1548625365-8f9c18f0ca78?w=600&q=80",
  },
  {
    id: 4,
    title: "Asian Fusion",
    description: "A creative, artistic grooming style inspired by Asian trends. Perfect for pets who want a unique, trendy look.",
    price: "$95",
    duration: "120 min",
    image: "https://images.unsplash.com/photo-1591769225440-811ad7d6eab1?w=600&q=80",
  },
  {
    id: 5,
    title: "Cat Grooming",
    description: "Gentle, stress-free grooming for cats including bath, brush, nail trim, and a hygienic session tailored to feline needs.",
    price: "$55",
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1596854407944-bf87f85f138f?w=600&q=80",
  },
  {
    id: 6,
    title: "Puppy Grooming",
    description: "A gentle introduction to grooming for puppies. Builds positive associations while they get clean and tidy.",
    price: "$40",
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80",
  },
  {
    id: 7,
    title: "Senior Pet Grooming",
    description: "Extra gentle grooming for senior pets. Shorter sessions, extra comfort, and specialized handling for older animals.",
    price: "$45",
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&q=80",
  },
  {
    id: 8,
    title: "Nail Trimming",
    description: "Professional nail trimming with care. We use premium clippers and ensure a stress-free experience.",
    price: "$15",
    duration: "15 min",
    image: "https://images.unsplash.com/photo-1548625149-d9f1e9ae3cc0?w=600&q=80",
  },
  {
    id: 9,
    title: "Ear Cleaning",
    description: "Thorough ear cleaning using gentle, pet-safe solutions to prevent infections and keep ears healthy.",
    price: "$18",
    duration: "15 min",
    image: "https://images.unsplash.com/photo-1598136490941-1d39cc91d484?w=600&q=80",
  },
  {
    id: 10,
    title: "Hair Styling",
    description: "Professional creative styling and scissoring for breeds requiring special attention to coat aesthetics.",
    price: "$65",
    duration: "75 min",
    image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&q=80",
  },
  {
    id: 11,
    title: "Deshedding",
    description: "Specialized deshedding treatment that removes loose undercoat, reducing shedding around your home by up to 90%.",
    price: "$45",
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1568572933382-74d440642117?w=600&q=80",
  },
  {
    id: 12,
    title: "Spa Treatment",
    description: "The ultimate spa experience: aromatherapy bath, coconut conditioning, paw massage, and a soothing blow-dry.",
    price: "$85",
    duration: "90 min",
    image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80",
  },
  {
    id: 13,
    title: "Teeth Cleaning",
    description: "Gentle teeth brushing with pet-safe enzymatic toothpaste to promote dental health and fresh breath.",
    price: "$20",
    duration: "15 min",
    image: "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&q=80",
  },
  {
    id: 14,
    title: "Tick Treatment",
    description: "Thorough tick check and safe removal. Includes preventative treatment to protect your pet from parasites.",
    price: "$25",
    duration: "20 min",
    image: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80",
  },
]

export const teamMembers = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Master Groomer & Founder",
    experience: "12 years",
    specialization: "Asian Fusion & Creative Styling",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80",
    certifications: "IPG Master Groomer, NDGAA Certified",
  },
  {
    id: 2,
    name: "Michael Chen",
    role: "Senior Pet Stylist",
    experience: "8 years",
    specialization: "Breed-Specific Grooming",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    certifications: "AKC Groomer Certified",
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    role: "Cat Grooming Specialist",
    experience: "6 years",
    specialization: "Feline Grooming & Behavior",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80",
    certifications: "CFA Feline Grooming Certified",
  },
  {
    id: 4,
    name: "David Park",
    role: "Master Groomer",
    experience: "10 years",
    specialization: "Luxury Spa Treatments",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    certifications: "IPG Certified, Pet First Aid",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Jennifer Adams",
    petName: "Buddy",
    petType: "Golden Retriever",
    rating: 5,
    text: "Absolutely incredible service! My golden retriever Buddy has never looked better. The team took such good care of him, and he came back happy and smelling amazing. Highly recommend!",
    customerImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    petImage: "https://images.unsplash.com/photo-1553882809-a4f57e595701?w=200&q=80",
  },
  {
    id: 2,
    name: "Robert Kim",
    petName: "Luna",
    petType: "Persian Cat",
    rating: 5,
    text: "I was nervous about grooming my Persian cat, but the cat grooming specialist was amazing. Luna was calm throughout and looks absolutely gorgeous. Thank you for the gentle care!",
    customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    petImage: "https://images.unsplash.com/photo-1596854407944-bf87f85f138f?w=200&q=80",
  },
  {
    id: 3,
    name: "Maria Santos",
    petName: "Charlie",
    petType: "Cockapoo",
    rating: 5,
    text: "The Asian Fusion grooming style exceeded my expectations. Charlie looked like a show dog! The attention to detail and the luxurious spa treatment made it a wonderful experience.",
    customerImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    petImage: "https://images.unsplash.com/photo-1591769225440-811ad7d6eab1?w=200&q=80",
  },
  {
    id: 4,
    name: "James Wilson",
    petName: "Max",
    petType: "German Shepherd",
    rating: 5,
    text: "The deshedding treatment was a game-changer! Max's coat is so much healthier, and our furniture finally gets a break. Professional, clean, and truly caring staff.",
    customerImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    petImage: "https://images.unsplash.com/photo-1558941830-af3b54aadeb2?w=200&q=80",
  },
]

export const faqs = [
  {
    question: "How long does grooming take?",
    answer: "Grooming times vary by service and pet size. A basic bath and brush typically takes 45-60 minutes, while full grooming sessions can take 90-120 minutes. We always provide an estimated completion time when you drop off your pet.",
  },
  {
    question: "Do you groom cats?",
    answer: "Yes! We have a dedicated cat grooming specialist and a separate calm environment for cats. We understand cats have different needs and sensitivities, so we tailor our approach to ensure a stress-free experience.",
  },
  {
    question: "What products do you use?",
    answer: "We use only premium, organic, pet-safe products. Our shampoos are sulfate-free, hypoallergenic, and specially formulated for different coat types and skin conditions. We also offer fragrance-free options for sensitive pets.",
  },
  {
    question: "Can I stay during grooming?",
    answer: "We find that most pets actually do better without their owners present, as they can become excited or anxious. However, you're welcome to wait in our comfortable lounge area with complimentary coffee and WiFi.",
  },
  {
    question: "How often should my pet be groomed?",
    answer: "We recommend grooming every 4-6 weeks for most breeds. Regular grooming maintains coat health, prevents matting, and allows us to check for any skin issues early. Our team will recommend a schedule based on your pet's specific needs.",
  },
  {
    question: "What if my pet is anxious or aggressive?",
    answer: "Our groomers are trained in fear-free handling techniques. We can work with anxious pets using patience, positive reinforcement, and sometimes shorter sessions. For aggressive pets, we may recommend a consultation first to determine the best approach.",
  },
]

export const blogPosts = [
  {
    id: 1,
    title: "5 Essential Tips for Maintaining Your Dog's Coat Between Grooming Sessions",
    excerpt: "Learn how to keep your furry friend looking their best with these professional grooming tips for home care.",
    category: "Dog Care",
    image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80",
    date: "Jun 12, 2026",
    readTime: "5 min read",
  },
  {
    id: 2,
    title: "Understanding Your Cat's Grooming Needs: A Complete Guide",
    excerpt: "Cats have unique grooming requirements. Discover what every cat owner should know about feline coat care.",
    category: "Cat Care",
    image: "https://images.unsplash.com/photo-1596854407944-bf87f85f138f?w=600&q=80",
    date: "Jun 8, 2026",
    readTime: "4 min read",
  },
  {
    id: 3,
    title: "Seasonal Grooming: Preparing Your Pet for Summer",
    excerpt: "Summer is coming! Here's how to keep your pet comfortable, cool, and looking great during the hot months.",
    category: "Seasonal Grooming",
    image: "https://images.unsplash.com/photo-1553882809-a4f57e595701?w=600&q=80",
    date: "Jun 1, 2026",
    readTime: "6 min read",
  },
]

export const galleryImages = [
  { id: 1, src: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&q=80", alt: "Happy dog after grooming", category: "Happy Pets" },
  { id: 2, src: "https://images.unsplash.com/photo-1596854407944-bf87f85f138f?w=600&q=80", alt: "Cat grooming session", category: "Spa Treatment" },
  { id: 3, src: "https://images.unsplash.com/photo-1553882809-a4f57e595701?w=600&q=80", alt: "Golden retriever groomed", category: "Before & After" },
  { id: 4, src: "https://images.unsplash.com/photo-1591769225440-811ad7d6eab1?w=600&q=80", alt: "Creative grooming style", category: "Happy Pets" },
  { id: 5, src: "https://images.unsplash.com/photo-1548625365-8f9c18f0ca78?w=600&q=80", alt: "Salon interior", category: "Salon Interior" },
  { id: 6, src: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&q=80", alt: "Spa treatment", category: "Spa Treatment" },
  { id: 7, src: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&q=80", alt: "Dog styling", category: "Before & After" },
  { id: 8, src: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&q=80", alt: "Puppy grooming", category: "Happy Pets" },
]
